---
stages:
  - test
  - build
  - release

variables:
  SEMVER_PREFIX: v

.go_template_defaults:
  stage: test
.semver_template_defaults:
  stage: release
include:
  - { project: bonsai-oss/organization/automate/ci-templates, file: templates/language/go.yml }
  - { project: bonsai-oss/organization/automate/ci-templates, file: templates/release/semver.yml }

compile:
  stage: build
  image: golang:1.20.3-bullseye
  script:
    - mkdir -p binaries
    - go build -o binaries/openzfs_exporter-$(uname -s) ./cmd/openzfs_exporter/*.go
  parallel:
    matrix:
      - GOOS:
          - linux
          - freebsd
  artifacts:
    paths:
      - binaries