---
default:
  image: golang:latest

stages:
  - test
  - build

format:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

compile:
  stage: build
  script:
    - mkdir -p binaries
    - go build -o binaries/openzfs_exporter_$(uname -s) ./...
  parallel:
    matrix:
      - GOOS:
          - linux
          - freebsd
  artifacts:
    paths:
      - binaries

